'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';

type Profile={id:string;display_name:string|null;bio:string|null;avatar_url:string|null;city:string|null};
export default function Discover(){const [profiles,setProfiles]=useState<Profile[]>([]);const [loading,setLoading]=useState(true);const [user,setUser]=useState<string|null>(null);
useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();setUser(user?.id??null);const {data}=await supabase.from('profiles').select('id,display_name,bio,avatar_url,city').limit(24);setProfiles(data??[]);setLoading(false)})()},[]);
return <main className="shell page"><nav className="nav"><Link href="/" className="brand gold">Whale Love</Link><div className="row"><Link className="btn" href="/random-chat">🎲 رندوم</Link><Link className="btn" href="/chat">💬 چت</Link></div></nav><div className="row between" style={{margin:'22px 0'}}><div><h2 style={{marginBottom:4}}>Discover</h2><span className="muted">آدم‌های جدید را پیدا کن</span></div></div>{loading?<p className="muted">در حال بارگذاری...</p>:profiles.length===0?<section className="glass content center"><h3>هنوز پروفایلی پیدا نشد</h3><p className="muted">اول پروفایل خودت را کامل کن یا بعداً دوباره امتحان کن.</p></section>:<section className="grid cards">{profiles.filter(p=>p.id!==user).map(p=><article className="glass card" key={p.id}><div className="avatar" style={p.avatar_url?{backgroundImage:`url(${p.avatar_url})`,backgroundSize:'cover',backgroundPosition:'center'}:{}}><div><b>{p.display_name||'Whale User'}</b><div className="muted">{p.city||'نزدیک شما'}</div></div></div><div className="content"><p className="muted">{p.bio||'برای آشنایی بیشتر وارد پروفایل شوید.'}</p><div className="actions"><button className="btn primary">❤️ پسندیدن</button><Link className="btn" href={`/chat?user=${p.id}`}>چت</Link></div></div></article>)}</section>}<nav className="mobileNav glass"><Link className="active" href="/discover">کشف</Link><Link href="/random-chat">رندوم</Link><Link href="/chat">چت</Link><Link href="/profile">پروفایل</Link></nav></main>}
