'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';

type Profile={id:string;display_name:string|null;bio:string|null;avatar_url:string|null;city:string|null;is_verified?:boolean};
export default function Discover(){const [profiles,setProfiles]=useState<Profile[]>([]);const [loading,setLoading]=useState(true);const [user,setUser]=useState<string|null>(null);const [busy,setBusy]=useState<string|null>(null);const [notice,setNotice]=useState('');
useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='/login';return}setUser(user.id);const {data}=await supabase.from('profiles').select('id,display_name,bio,avatar_url,city,is_verified').neq('id',user.id).eq('discoverable',true).order('is_online',{ascending:false}).limit(24);setProfiles(data??[]);setLoading(false)})()},[]);
async function like(id:string){setBusy(id);setNotice('');const {data,error}=await supabase.rpc('like_profile',{target_user:id});setBusy(null);if(error){setNotice(error.message);return}if(data?.[0]?.matched){setNotice('🎉 مچ شدید! گفت‌وگو آماده است.');setTimeout(()=>location.href=`/chat?user=${id}`,500)}else setNotice('❤️ پسند شما ثبت شد.')} 
return <main className="shell page"><nav className="nav"><Link href="/" className="brand gold">Whale Love</Link><div className="row"><Link className="btn" href="/random-chat">🎲 رندوم</Link><Link className="btn" href="/chat">💬 چت‌ها</Link></div></nav><div className="row between" style={{margin:'22px 0'}}><div><h2 style={{marginBottom:4}}>Discover</h2><span className="muted">آدم‌های جدید را پیدا کن</span></div><Link className="btn" href="/profile">ویرایش پروفایل</Link></div>{notice&&<div className="glass content gold" style={{marginBottom:16}}>{notice}</div>}{loading?<p className="muted">در حال بارگذاری...</p>:profiles.length===0?<section className="glass content center"><h3>هنوز پروفایلی پیدا نشد</h3><p className="muted">پروفایل خودت را کامل کن و کمی بعد دوباره امتحان کن.</p></section>:<section className="grid cards">{profiles.map(p=><article className="glass card" key={p.id}><div className="avatar" style={p.avatar_url?{backgroundImage:`url(${p.avatar_url})`,backgroundSize:'cover',backgroundPosition:'center'}:{}}><div><b>{p.display_name||'Whale User'} {p.is_verified?'✓':''}</b><div className="muted">{p.city||'نزدیک شما'}</div></div></div><div className="content"><p className="muted">{p.bio||'برای آشنایی بیشتر وارد گفت‌وگو شوید.'}</p><div className="actions"><button disabled={busy===p.id} className="btn primary" onClick={()=>like(p.id)}>{busy===p.id?'...':'❤️ پسندیدن'}</button><Link className="btn" href={`/chat?user=${p.id}`}>چت</Link></div></div></article>)}</section>}<nav className="mobileNav glass"><Link className="active" href="/discover">کشف</Link><Link href="/random-chat">رندوم</Link><Link href="/chat">چت</Link><Link href="/profile">پروفایل</Link></nav></main>}
